AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.0
  Exclude:
    - "config/routes/**/*"
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "node_modules/**/*"
    - "app/controllers/api/**/*"
    - "app/serializers/api/**/*"
    - "app/controllers/concerns/api/**/*"
    - "spec/serializers/api/**/*"
    - "spec/requests/api/**/*"
    - "spec/requests/shared/**/*"

require:
  - rubocop-rails
  - rubocop-rspec

######### Layout #########
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/LineLength:
  Max: 80
  Exclude:
    - db/schema.rb
    - config/initializers/devise.rb

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

######### Lint #########
Lint/Debugger:
  Exclude:
    - db/seeds/*.rb

######### Metrics #########
Metrics/BlockLength:
  Max: 15
  AllowedMethods:
    - included
    - class_methods
  Exclude:
    - app/models/user/event_handlers/**/*
    - config/environments/*
    - config/initializers/*
    - config/routes.rb
    - config/routes/**/*
    - db/seeds/*.rb
    - db/seeds.rb
    - spec/*_helper.rb
    - spec/models/budget/change_set/setup_spec.rb
    - spec/requests/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 18
  Exclude:
    - app/models/user/session/data.rb
    - db/seeds/budget_interval.rb

######### Rails ##########
Rails/ApplicationController:
  Enabled: false

Rails/TimeZone:
  Enabled: false

######### Style #############
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: never

Style/GlobalVars:
  AllowedVariables:
    - $logger

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/MultilineBlockChain:
  Enabled: false

Style/MutableConstant:
  EnforcedStyle: literals

Style/RedundantFreeze:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

######### RSpec #########
RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/ExampleLength:
  Max: 100
  Exclude:
    - spec/requests/api/**/*
    - spec/serializers/**/*
    - spec/models/budget/change_set/setup_spec.rb

RSpec/IndexedLet:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
  Exclude:
    - spec/models/budget/events/*_spec.rb

RSpec/NotToNot:
  EnforcedStyle: not_to

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 9
  Exclude:
    - spec/lib/forms/**/*
    - spec/requests/api/**/*
    - spec/serializers/**/*
    - spec/models/budget/**/*
