AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.0
  Exclude:
    - "config/routes/**/*"
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "node_modules/**/*"

require:
  - rubocop-rails
  - rubocop-rspec

Rails/TimeZone:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - db/schema.rb
    - config/initializers/devise.rb

Metrics/BlockLength:
  Max: 15
  AllowedMethods:
    - included
    - class_methods
  Exclude:
    - app/models/user/event_handlers/**/*
    - config/environments/*
    - config/initializers/*
    - config/routes.rb
    - config/routes/**/*
    - db/seeds/*.rb
    - db/seeds.rb
    - spec/*_helper.rb
    - spec/models/budget/change_set/setup_spec.rb
    - spec/requests/**/*

Lint/Debugger:
  Exclude:
    - db/seeds/*.rb

Metrics/MethodLength:
  Max: 18
  Exclude:
    - app/models/user/session/data.rb
    - db/seeds/budget_interval.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/GlobalVars:
  AllowedVariables:
    - $logger

Style/MultilineBlockChain:
  Enabled: false

Style/RedundantFreeze:
  Enabled: true

Style/MutableConstant:
  EnforcedStyle: literals

Rails/ApplicationController:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - spec/requests/api/**/*
    - spec/serializers/**/*
    - spec/models/budget/change_set/setup_spec.rb

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
  Exclude:
    - spec/models/budget/events/*_spec.rb

RSpec/NotToNot:
  EnforcedStyle: not_to

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 9
  Exclude:
    - spec/lib/forms/**/*
    - spec/requests/api/**/*
    - spec/serializers/**/*
    - spec/models/budget/**/*

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/IndexedLet:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
