AllCops:
  TargetRubyVersion: 3.2.0
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'node_modules/**/*'

require:
  - rubocop-rails
  - rubocop-rspec

Layout/LineLength:
  Max: 120
  Exclude:
    - db/schema.rb
    - config/initializers/devise.rb

Metrics/BlockLength:
  Max: 10
  Exclude:
    - app/models/user/event_handlers/**/*
    - config/environments/*
    - config/initializers/*
    - config/routes.rb
    - spec/*_helper.rb
    - spec/requests/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/GlobalVars:
  AllowedVariables:
    - $logger

Style/MultilineBlockChain:
  Enabled: false

Style/RedundantFreeze:
  Enabled: true

Style/MutableConstant:
  EnforcedStyle: literals

Rails/ApplicationController:
  Exclude:
    - app/controllers/home_controller.rb

RSpec/ExampleLength:
  Max: 10

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
  Exclude:
    - spec/models/budget/events/*_spec.rb

RSpec/NotToNot:
  EnforcedStyle: not_to

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 9

RSpec/MessageSpies:
  EnforcedStyle: receive
